fengines:
    chans_per_packet: 96
    snap01:
        ants: [0, 32]
        gbe: '10.41.0.101'
        source_port: 10000
        dest_port: 10000
    snap02:
        ants: [32, 64]
        gbe: '10.41.0.102'
        source_port: 10000
        dest_port: 10000
    snap03:
        ants: [64, 96]
        gbe: '10.41.0.103'
        source_port: 10000
        dest_port: 10000
    snap04:
        ants: [96, 128]
        gbe: '10.41.0.104'
        source_port: 10000
        dest_port: 10000
    snap05:
        ants: [128, 160]
        gbe: '10.41.0.105'
        source_port: 10000
        dest_port: 10000
    snap06:
        ants: [160, 192]
        gbe: '10.41.0.106'
        source_port: 10000
        dest_port: 10000
    snap07:
        ants: [192, 224]
        gbe: '10.41.0.107'
        source_port: 10000
        dest_port: 10000
    snap08:
        ants: [224, 256]
        gbe: '10.41.0.108'
        source_port: 10000
        dest_port: 10000
    snap09:
        ants: [256, 288]
        gbe: '10.41.0.109'
        source_port: 10000
        dest_port: 10000
    snap10:
        ants: [288, 320]
        gbe: '10.41.0.110'
        source_port: 10000
        dest_port: 10000
    snap11:
        ants: [320, 352]
        gbe: '10.41.0.111'
        source_port: 10000
        dest_port: 10000

xengines:
  arp:
    # lwa-gpu02
    10.41.0.17: 0x043f72d0b116
    10.41.0.33: 0x043f72d0b106
  chans:
    # lwa-gpu02
    10.41.0.17: [0, 192]
    10.41.0.33: [192, 384]

